app/contact/page.tsx, app/cookie/page.tsx, components/ui/table.tsx, package-lock.json, package.json
Still needs some touching after the neccesary components are built
=> feat: implemented contact and cookie pages

README.md
Refined the README.md file to fit the project.
=> docs: refine README.md file

package.json
=> cicd update

app/(dashboard)/dashboard/page.tsx
Implementation of the ui design for the dashboard page
=> feat: create dashboard

app/(dashboard)/dashboard/page.tsx
I added the correct table headings and worked on the design for the mobile version
=> fix: add correct table headings

components/functional/footer.tsx
I have resolved design issues on the homepage to align with the Figma design.
These changes ensure a consistent and visually appealing homepage, improving the user experience. 
I updated the homepage styles using a HTML attribute
I verified that the homepage displays correctly across different screen sizes and browsers. I also compared it with the Figma design to ensure consistency.
=> fix: resolve design issue on homepage

app/(dashboard)/dashboard/page.tsx
I added separators between the table head elements to align with the intended design.
=> fix: add divider to table header elements

app/(auth)/sign-in/_components/SignIn.tsx, app/(auth)/sign-in/_components/logout.tsx, app/(dashboard)/dashboard/page.tsx, app/(landing)/page.tsx, app/api/auth/logout/route.ts, components/functional/loading.tsx, components/modal/add-item.tsx, package-lock.json, package.json
- Implemented logout functionality and authorized the dashboard.
- Redesigned the add-stock modal and dashboard for better UI/UX.
- Added animations to the landing page for a smoother user experience.
- Improved security by ensuring only authorized users can access the dashboard.
- The previous design of the add-stock modal and dashboard needed refinement to align with the latest UI guidelines.
- Enhancing user engagement with animations on the landing page.
- Edited authentication logic to handle logout and user authorization.
- Updated the structure and styling of the add-stock modal and dashboard using Tailwind CSS.
- Integrated animations using AOS for an improved user experience on the landing page.
- Manually tested logout and ensured unauthorized users are redirected.
- Verified UI …
=> fix: dashboard and modal redesigned

app/(dashboard)/dashboard/page.tsx, components/modals/edit-stock.tsx
Fixed the edit modal to open when "Edit" is clicked and updated the table to display 10 rows of added stock items.
To enable users to view their stocks and also edit them as they need.
matched the edit modal to that of design and used ui components such as table, to map stock details and dropdown to view button like edit and delete.
Verified modal opens when edit is clicked and data is displayed correctly as needed.
=> Fixed edit modal trigger and updated table display for added items

app/(dashboard)/dashboard/page.tsx, components/modal/add-item.tsx, components/modal/delete-item.tsx, components/modal/edit-stock.tsx
I added Edit, add, and delete functionality in the dashboard.
I'm ensuring proper CRUD (Create, Read, Update, Delete) functionality in the dashboard, allowing users to manage stock items efficiently. This improves usability and data management, making the system more dynamic and user-friendly.
Add: New stock items are added by calculating the next id based on the existing items and updating the state with the new entry.
Edit: Stock items are updated by mapping through the array, finding the item by id, and replacing it with the updated data.
Delete: Items are removed by filtering out the selected id from the stock items array.
All changes are handled using useState, ensuring the UI updates dynamically.
I've tested the login functionality with valid and invalid credentials. I also verified …
=> Feat/hng 2145 add, edit, delete

app/(dashboard)/dashboard/page.tsx, app/api/auth/login/route.ts, app/api/auth/refresh/route.ts
- **feat: store access and refresh tokens in secure cookies**
- **feat: implement access token refresh logic**
This pull request introduces two main features:
- Securely storing access and refresh tokens in cookies to improve client-side authentication.
- Implementing access token refresh logic to ensure continuous user sessions without requiring re-authentication.
Access & Refresh Token Storage
- Tokens are stored in HTTP-only and secure cookies to prevent access from client-side scripts.
- Cookies are set with appropriate lifespans:
- Access token: 15 minutes (maxAge: 60 * 15)
- Refresh token: 3 days (maxAge: 60 * 60 * 24 * 3)
- Access Token Refresh Mechanism
- **Implemented a helper function refreshAccessToken() to:**
- Retrieve the refresh token from cookies.
- Call the external API …
=> feat: save tokens in cookies and implement access token refresh

app/(dashboard)/dashboard/page.tsx, components/functional/paginationExample.tsx, components/functional/paginationfeature.tsx, components/ui/button.tsx, components/ui/pagination.tsx
i have added the pagination
This is for switching pages 
this include diff option of pages depending on how many stocks the user is viewing
test and working
=> feat:HNG-2145-add-pagination

app/(dashboard)/dashboard/page.tsx
I've updated the v1.2 branch to align with the latest changes in main. This ensures that v1.2 is up-to-date with the most recent developments.
Keeping v1.2 in sync with main prevents conflicts and ensures that the latest features, bug fixes, and improvements are available in the branch. This update was necessary to maintain consistency across development efforts.
I merged main into v1.2, resolving any conflicts and verifying that all changes integrate smoothly.
I've tested the updated branch to confirm that everything works as expected and that no functionality is broken after the merge
=> fix: fixed the whole v1.2 brach to meet up with main branch

app/(auth)/sign-in/_components/SignIn.tsx, app/api/email/login/route.ts, lib/utils.ts, services/loginEmail.ts
- Implements the logic to send a welcome email when a user successfully logs in.
- To enhance the user experience by confirming successful login via email.
1. Log in as a user.
2. Check the email inbox for a welcome message."
=> feat: implement sending welcome email to useer on successful login

components/modal/components/testcomp.tsx, components/modal/delete-image.tsx, components/modal/edit-image.tsx
What I Did
Added the EditImage Component:
Created a new EditImage component to allow users to edit and manage saved images.
The component displays all saved images in a modal, with a "remove" icon (✕) for each image.
Clicking the "remove" icon triggers a confirmation modal (DeleteImage) to delete the image.
Refactored the DeleteImage Component:
Updated the DeleteImage component to work seamlessly with the EditImage component.
The DeleteImage modal now handles the actual deletion of images and provides a confirmation UI.
Created a Test Parent Component:
Added a TestParentComponent to test the EditImage and DeleteImage functionality.
The test component includes a pre-populated list of images and an "Edit Images" button to open the EditImage modal.
Improved Code Structure:
Separated concerns …
=> feat: add deleteImage and Edit image feature

components/functional/sidebar.tsx, components/modal/modalV3/edit-name.tsx, components/modal/modalV3/edit-quantity.tsx, services/stock.ts
the pr introduces a new feature that allows users to edit their stock details directly from a sidebar modal. The feature includes:
- An edit navigation on the stock detail.
- Edit modals to modify the different selected fields. 
- A success modal that appears after a successful update.
This feature addresses the user need to efficiently update stock details without navigating away from the current view. It improves the user experience by providing an effective way to make changes, ensuring that updates are quick and error-free.
- Implemented a modal component that opens when the edit button is clicked, allowing users to modify the selected field.
- Integrated a success modal to confirm updates and provide feedback to the user.
- Used state management to handle form inputs and validation. …
=> update: update product details on  design

app/(dashboard)/dashboard/page.tsx, components/functional/paginationfeature.tsx, public/icons/search_Icon.svg
This PR improves the responsiveness of the pagination feature by using container queries to ensure it adapts properly when the sidebar opens or the screen size changes. The pagination component now adjusts its layout dynamically based on the available space, preventing layout breaks and improving the user experience.
Changes Made:
Added Container Queries:
Wrapped the PaginationFeature component in a div with the class pagination-container.
Defined container queries in global.css to adjust the layout when the container size is small (e.g., when the sidebar is open).
Improved Responsiveness:
Stacked pagination controls vertically on small screens.
Centered the pagination info text.
Hid some pagination items (e.g., page numbers) on small screens to save space.
Made "Previous" and "Next" …
=> Improve Pagination Responsiveness with Container Queries

app/(auth)/sign-in/_components/SignIn.tsx, app/(auth)/sign-in/page.tsx, app/(auth)/sign-up/page.tsx
I have added support for user authentication by implementing the sign-up feature as per the Figma design. This includes the sign-up page.
These changes complete the user registration experience, allowing new users to securely create an account and access the platform. 
This includes a new sign-up page built with Next.js and Tailwind CSS. I used shadcn/ui for reusable components like the dropdown. The form includes validation to ensure users enter valid information.
- Tested the sign-up functionality with valid and invalid credentials.
- Verified that error messages display correctly for invalid inputs.
- Ensured the UI matches the Figma design and maintains responsiveness.
=> feat: sign up page

.github/workflows/test.yml, docker-compose.yml
Added docker-compose file for monitoring with prometheus, grafana, node exporter and blackbox
=> Monitoring update

blackbox.yml, docker-compose.yml, prometheus.yml
Add prometheus.yml and blackbox.yml configurations.
=> Create monitoring configurations.

app/(auth)/create-organization/_components/CreateOrganization.tsx, public/icons/Close_Buttons.svg
Feat: create organization is part of the sign up process for a user.
=> feat: create-organization feature was built and successfully responsive

alertmanager.yml, docker-compose.yml, prometheus.yml
Created Alert manager service in docker compose file and update prometheus.yml and alertmanager.yml
=> Added Alertmanager

alertmanager.yml, prometheus.yml
edited alert manager and prometheus.yml
=> Alert manager update

app/(auth)/create-organization/_components/CreateOrganization.tsx
I made adjustments based on the new design.
i added a new form field for users to input their address.
=> I added new form field which is full address

components/modal/add-item.tsx
This PR implements the new design for the Add Item Modal to align with the updated and improved design specifications. The changes include:
- Updated UI components to match the new design.
- Ensured proper rendering of all error messages.
- Improved user experience with a more intuitive and visually appealing layout.
The current Add Item Modal does not match the new design standards, leading to inconsistencies in the user interface. This update ensures:
- A cohesive look and feel across the application.
- Better user experience with clear error handling and feedback.
- Alignment with the latest design guidelines.
- Refactored the modal components to match the new design.
- Added proper validation and error handling to ensure all errors are displayed correctly.
- Ensured responsive …
=> update:updated the add item modal to new design

app/(marketing)/ecommerce/components/Hero.tsx
Merge from dev to staging branch for testing
=> feat: add video to ecommerce landing page

app/(app)/stock/components/data-table.tsx, app/(app)/stock/page.tsx, components/functional/sidebar.tsx, redux/features/sidebar/index.ts, redux/features/sidebar/sidebar.slice.ts, redux/store.ts
This PR introduces the following changes:
1. Uncommented the datatable component: The datatable component is integrated with the sidebar.
2. Added sidebar rendering to the datatable: The sidebar now renders dynamically when a row in the datatable is clicked.
3. Refactored sidebar code: Fixed issues with the sidebar code and ensured state management is properly handled.
4. Added sidebar state reducer to the store: A new reducer for managing sidebar state has been added to the Redux store.
5. Exported sidebar slice and reducers: The sidebar slice and reducers are now exported for use in other parts of the application.
6. Created sidebar slice file: A new file for the sidebar slice has been created to manage sidebar-related state.
Changes
- Uncommented datatable component and integrated it …
=> feat: Integrate sidebar with datatable and add state management

.github/workflows/deploy.yml
=> update on deploy.yml

app/(dashboard)/dashboard/page.tsx, components/modal/salesmodal/receipt-item.tsx, components/modal/salesmodal/sales-modal.tsx, components/modal/salesmodal/search-bar.tsx, components/modal/salesmodal/stock-item-card.tsx, redux/slicer.ts, redux/store.ts
I've refactored the sales modal by breaking it down into reusable components, improving maintainability and readability. The refactoring includes better state management using Redux and enhanced UI structuring.
This refactor makes the codebase cleaner and more modular, improving reusability and scalability. It also enhances performance by minimizing unnecessary re-renders. For more background, see ticket #HNG-2145.
Separated concerns by creating individual components for ItemCard, ReceiptItem, and SearchBar.
Improved state management with Redux, ensuring better control over selected items and active state updates.
Optimized list rendering using useMemo for filtering stock items and calculating totals efficiently.
Enhanced UI with better responsive behavior using Tailwind CSS.
I've tested …
=> Improved Sales Modal with Modular Components

app/(dashboard)/dashboard/components/Account.tsx, app/(dashboard)/dashboard/components/Buisness.tsx, app/(dashboard)/dashboard/components/Footer.tsx, app/(dashboard)/dashboard/components/Header.tsx, app/(dashboard)/dashboard/components/Settings.tsx, app/(dashboard)/dashboard/components/TableContent.tsx, app/(dashboard)/dashboard/components/billing.tsx, app/(dashboard)/dashboard/components/notification.tsx, app/(dashboard)/dashboard/components/stockpreference.tsx, app/(dashboard)/dashboard/components/userpermission.tsx, redux/notificationlslice.ts, redux/store.ts
I've implemented the Notification Settings tab within the Settings page. This includes UI components for managing different types of notifications (Order Notifications, Sales Reports, and Payment Notifications) with toggle switches and dropdowns.
This feature allows users to customize how they receive notifications related to their store, improving user experience and engagement.
Created a Notification component to structure the settings page.
Used React and Redux to manage notification states.
Added ToggleSwitch components to enable/disable notifications.
Included select dropdowns for choosing notification methods (Email, Push, SMS).
Styled using Tailwind CSS for a clean and responsive UI.
Verified that toggles update Redux state correctly.
Ensured dropdowns correctly reflect and update …
=> Implemented the notification tab UI on the settings page

app/(dashboard)/dashboard/components/stockpreference.tsx, app/(dashboard)/dashboard/page.tsx, bun.lock
I've implemented a stock settings UI that includes options for currency selection, payment methods, tax settings, and inventory management. This UI allows users to configure their store preferences easily.
These changes improve the user experience by providing a structured and intuitive way for users to manage their stock settings. This aligns with the overall goal of enhancing store customization and business operations.
The implementation includes:
Stock Header: Displays a section title and a brief description.
Custom Dropdown: Used for selecting currency and tax type.
Currency Selection: Allows users to set their preferred currency.
Payment Options: Users can enable or disable payment methods like bank transfer, PayPal, and Stripe.
Account Details: Input field for entering relevant …
=> Implement the stockprefence tab Stock Management in Settings

app/(dashboard)/dashboard/components/Header.tsx, app/(dashboard)/dashboard/components/TableContent.tsx, components/functional/paginationfeature.tsx, components/functional/sidebar.tsx, components/modal/logoutConfirmationModal.tsx
fixed: sidebar 
pagination ui
logoutconfirmation button color
table content overflow
screenshot :
=> fix: sidebar, pagination, logout confirmation fix

app/(dashboard)/dashboard/components/Header.tsx, app/(dashboard)/dashboard/components/TableContent.tsx, components/functional/paginationfeature.tsx, components/functional/sidebar.tsx, components/modal/logoutConfirmationModal.tsx
Reverts hngprojects/shopdesk-fe#228
=> Revert "fix: sidebar, pagination, logout confirmation fix"

components/modal/edit-stock.tsx, components/modal/modalV3/edit-name.tsx, components/modal/modalV3/edit-price.tsx, components/modal/modalV3/edit-quantity.tsx, services/stock.ts, store/useStore.ts
Implemented edit stock functionality.
=> Feat: Implemented edit stock functionality.

app/api/product/create/route.ts, app/api/productPrices/route.ts, app/api/stocks/create/route.ts, components/modal/add-item.tsx, redux/api.ts, redux/features/price/price.api.ts, redux/features/price/price.slice.ts, redux/features/product/product.api.ts
This pull request introduces the following changes related to the creation of products, pricing, and stock handling within the app:
- Implemented `createProduct` mutation inside `product.api.ts`.
- Refactored `products/create/route.ts` to retrieve the actual `access_token` directly from the user's cookies.
- Created the following for the pricing functionality:
- `price.api.ts`
- `price.slice.ts`
- `price` API route (`app/api/price/route.ts`)
- Integrated the full flow into `add-item.tsx`, enabling:
- Automatic product creation.
- Automatic price creation linked to the product.
- Stock creation after price and product setup.
- Verified and tested the UI, ensuring the end-to-end flow works as expected when adding a new stock.
---
- `product.api.ts`: Added `createProduct` mutation.
- …
=> feat: implement create product and product prices APIs to complete add stock flow

app/(dashboard)/(app)/sales/components/data-table-pagination.tsx, app/(dashboard)/(app)/sales/page.tsx
Did a  fix for the sales page freezing.
=> fix: bug fix sales

app/(landing)/contact/Contact.tsx, app/(landing)/contact/components/ContactForm.tsx, app/(landing)/contact/components/ContactHeader.tsx, app/(landing)/contact/components/ContactInfoCard.tsx, app/(landing)/contact/components/ContactInfoSection.tsx
Changes:
- Broke down the contact page into 5 reusable components
- Created dedicated components for header, form, and contact info sections
- Implemented proper TypeScript interfaces for all props
- Maintained all existing functionality and improved UI styling
- added animation sequences and responsive behavior
Benefits:
- Improved code organization and readability
- Increased component reusability
- Better separation of concerns
- Easier future maintenance
- More consistent prop typing
Testing:
- Verified all form fields work as before
- Confirmed all animations trigger correctly
- Checked responsive behavior across breakpoints
- Validated all contact links/actions
Screenshot:
=> refactor(contact): Componentize contact page for better maintainability

app/(dashboard)/(app)/layout.tsx, app/(dashboard)/(app)/sales/page.tsx, app/(dashboard)/(app)/stock/components/columns.tsx, app/(dashboard)/(app)/stock/components/data-table-column-header.tsx, app/(dashboard)/(app)/stock/components/data-table.tsx, app/(dashboard)/(app)/stock/components/editable-cell.tsx, app/(dashboard)/(app)/stock/page.tsx, app/api/stocks/edit/route.ts, redux/features/stock/stock.api.ts
I integrated the api for inline edit in the stocks table
=> feat: api inline edit

bun.lock, components/modal/modalV3/edit-price.tsx, package.json, redux/features/stock/stock.api.ts
This Pull Request addresses type errors that were identified during the build process. These fixes ensure adherence to the type definitions in the codebase.
- Ran the build process to uncover type-related errors in multiple files.
- Fixed the identified type errors to prevent build failures and improve reliability.
1. Pull this branch and install dependencies:
```bash
git pull origin <branch-name>
npm install
2. Run build to confirm successful compilation:
```bash
npm run build
=> Fix:  Fix Type Errors Discovered During Build

app/(dashboard)/(app)/sales/page.tsx, app/(dashboard)/(app)/stock/components/data-table-toolbar.tsx, app/(dashboard)/(app)/stock/components/data-table.tsx, components/dashboard/DashboardHeader.tsx, components/modal/add-item.tsx, components/modal/salesmodal/sales-modal.tsx, components/modal/salesmodal/stock-item-card.tsx
fix errors related to the tables
=> Fix: fix errors

app/(dashboard)/settings/components/stockpreference.tsx, app/(dashboard)/settings/layout.tsx, app/(dashboard)/settings/stock-preference/components/stock-header.tsx, redux/preferencesSlice.ts, redux/store.ts
I've implemented the complete Store Preferences management system with Redux state management. This includes:
Currency selection dropdown
Mutually exclusive payment options (Bank Transfer, PayPal, Stripe)
Account details input
Tax settings configuration
Inventory management controls
Fully functional Save and Cancel buttons
These changes enable store owners to customize their store settings according to business needs. The implementation addresses:
Ticket #FRA-80: Payment method selection(store prefence settings)
Ticket #FRA-81: Tab name type "Store preference" not :stock preference"
The solution provides a centralized way to manage all store settings with proper state persistence and validation.
The implementation includes:
Redux Toolkit Slice:
Created preferencesSlice with all store …
=> fix: Cancel and save buttons now functional

app/(landing)/pricing/_components/PriceCardOption.ts, app/(landing)/pricing/_components/Pricing.tsx, app/(landing)/pricing/page.tsx, public/pricing/checkbox.svg
Changes Implemented:
- Added checkbox SVG assets for consistent UI
- Restructured pricing page layout and components
- Implemented AOS animations for scroll effects
- Created separate data file for pricing options with TypeScript types
- Aligned UI with design specifications
- Fixed hover states and feature list alignment
- Removed "/mo" suffix from annual pricing displays
Technical Updates:
- Refactored component structure for better maintainability
- Added proper typing for pricing data
- Standardized animation implementation
- Resolved hover transition glitches
- Adjusted responsive behavior
Screenshot :
=> refactor:  Pricing Page Refactor

components/dashboard/DashboardHeader.tsx, store/useStore.ts
- Fix initials display name not showing
=> Fix: fix initials display name not showing

app/(dashboard)/(app)/sales/components/data-table-row-actions.tsx, app/(dashboard)/(app)/stock/components/data-table-row-actions.tsx
Removed 'make a copy option in dropdown'
=> Fix: Removed 'make a copy option in dropdown'

app/(dashboard)/(app)/stock/components/data-table-pagination.tsx, app/(landing)/page.tsx, components/providers/AuthProvider.tsx
Refactored the auth provider to fix recursive calling of refresh access token
=> fix: fix auth recursive refresh access token

app/(dashboard)/(app)/stock/components/columns.tsx, app/api/sales/profit/route.ts, app/api/sales/weekday-count/route.ts, redux/features/sale/sale.api.ts
=> feat: integrate weekly sales in stocks endpoint

app/(auth)/create-organization/page.tsx, app/(dashboard)/settings/components/Buisness.tsx, app/(dashboard)/settings/components/BusinessImage.tsx, app/api/organizationImage/route.ts, next.config.ts, redux/api.ts, redux/features/auth/auth.api.ts, redux/features/organizationImage/organizationImage.api.ts, services/getOrganization.ts
- **feat: implement API route and Redux integration for organization image (get & update)**
- **feat: add builder query for fetching organizations**
- **feat: configure remotePatterns, extract reusable component, and handle organization image fetch/update**
- **feat: add protection to create organization page**
- **fix: fix api route path**
- **feat: show toast notifications for successful and failed organization image updates**
- **refactor: change check for authentication to access_token**
This PR introduces the business image upload feature, along with necessary API integration, component refactoring, UI improvements, and toast notifications for better user feedback.
---
- Created API route and Redux API for getting and updating organization images.
- Added builder query for …
=> feat: Update Business Image

app/(dashboard)/(app)/sales/components/columns.tsx, app/(dashboard)/(app)/sales/page.tsx, app/(dashboard)/(app)/stock/components/columns.tsx, components/modal/salesmodal/components/product-list.tsx, components/modal/salesmodal/receipt-item.tsx, redux/features/sale/sale.api.ts
=> fix: stock table selling price to actual price and also update sales modal

app/(dashboard)/(app)/stock/components/data-table.tsx, app/(dashboard)/(app)/stock/page.tsx, app/api/product-images/route.ts, components/functional/sidebar.tsx, components/modal/add-image.tsx, components/modal/delete-image.tsx, components/modal/edit-image.tsx, redux/api.ts, redux/features/product/product.api.ts, redux/features/productImage/productImage.api.ts, redux/features/productImage/productImage.slice.ts, redux/store.ts
- **feat: implement API route for product images and set up Redux api for seamless API consumption and management.**
- **feat: implement adding, editing, and deleting product images in stocks sidebar**
- **chore: remove console.log**
- **fix: reset file input state to fix change event issues**
This PR introduces comprehensive product image handling capabilities, including API integration, Redux state management, and UI interactions in the stocks sidebar. The implementation covers the full CRUD lifecycle for product images with proper error handling and user feedback.
| Commit | Description |
|--------|-------------|
| `feat: implement API route for product images...` | Added backend API routes and Redux API slice |
| `feat: implement adding, editing, and deleting...` | Consumed the APIs, …
=> Implement Product Image Management In Sidebar
